### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
Hi all.

I updated windows managers on README.md(related in each distro-linux).

### CODE REVIEW

**Review by cafehaine — CHANGES_REQUESTED** [review]
Enlightenment is already present bellow with **WIP** in front of it

**Review by cafehaine — DISMISSED** [review]
Already marked as conpleted at the bottom of the list

**Comment by cafehaine** [comment]
Looks great otherwise, thanks !

**Review by ghost — COMMENTED** [review]
Hi all.

I removed duplicate: Budgie, Enlightenment, Deepin, Cinnamon etc.

**Comment by cafehaine** [comment]
Looks good to me, thanks a lot :)

**Comment by ghost** [comment]
Hi cafehaine.

> Looks good to me, thanks a lot :)

thank you for feedback.

**Pull request merged**
